export const PAGE_LOAD_NEW = "PAGE_LOAD_NEW";
export const PAGE_LOAD_SUCCESS = "PAGE_LOAD_SUCCESS";

export const PAGE_FOCUS_COMPONENT = "PAGE_FOCUS_COMPONENT";
export const PAGE_DELETE_COMPONENT = "PAGE_DELETE_COMPONENT";

export const PAGE_DELETE = "PAGE_DELETE";
export const PAGE_DELETE_START = "PAGE_DELETE_START";

export const PAGE_SHOW_COMPONENT_SIDEBAR = "PAGE_SHOW_COMPONENT_SIDEBAR";
export const PAGE_ADD_COMPONENT = "PAGE_ADD_COMPONENT";

export const PAGE_UPDATE_START = "PAGE_UPDATE_START";
export const PAGE_UPDATE_SUCCESS = "PAGE_UPDATE_SUCCESS";

export const PAGE_UPDATE_PROPERTY = "PAGE_UPDATE_PROPERTY";
export const PAGE_UPDATE_PROP = "PAGE_UPDATE_PROP";
export const PAGE_UPDATE_STATE = "PAGE_UPDATE_STATE";
